name = "activity-tracker-api"
compatibility_date = "2024-07-18"

[[d1_databases]]
binding = "DB"
database_name = "activity-tracker-prod"
database_id = "c6fff657-940c-4950-8f6b-349ffef0b932"
migrations_dir = "prisma/migrations"
