name = "activity-tracker-api"
compatibility_date = "2024-07-18"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "activity-tracker-prod"
database_id = "d8d74f67-8cb6-49e6-aee0-7bd85a6733a5"
migrations_dir = "prisma/migrations"
