name: Checks

on:
  push:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'api'
    - run: npm ci
    - name: Run linter
      run: npm run lint
    - name: Check TypeScript types
      run: npx tsc --noEmit
    - name: Run tests
      run: npm run test
  macos:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: macos
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: stanfordbdhg/action-swiftlint@v4
        with:
          args: --strict
        env:
          WORKING_DIRECTORY: macos
